[package]
name = "rustimgresizer"
version = "0.1.0"
authors = ["Urjit Singh Bhatia <urjitsb87@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.12"
rocket = "0.4.2"
pipe = "0.2.0"
statsd = "^0.9.0"

[profile.release]
debug=true
